apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-svc
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: postgres-replica
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres-replica
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
