apiVersion: v1
kind: Service
metadata:
  name: trading-db-svc
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: trading-db
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: trading-db
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
