apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      name: http
