apiVersion: v1
kind: Service
metadata:
  name: alert-router-svc
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: alert-router
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alert-router
  ports:
    - port: 8093
      targetPort: 8093
      name: http
