apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: disruption-budget
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
