apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
