apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  namespace: banka2-tim2
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: arbitro
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - port: 11434
      targetPort: 11434
      name: http
